# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='issue',
        ),
    ]
