# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0002_remove_citation_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='authors',
        ),
    ]
