# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0003_remove_citation_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
