# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0004_auto_20171029_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='keywords',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
