# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0005_auto_20171102_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='journal',
            field=models.CharField(max_length=512),
        ),
    ]
