# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0006_auto_20171103_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='date',
            field=models.CharField(default='missing', max_length=200),
        ),
        migrations.AlterField(
            model_name='citation',
            name='journal',
            field=models.CharField(default='missing', max_length=512),
        ),
        migrations.AlterField(
            model_name='citation',
            name='keywords',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='citation',
            name='volume',
            field=models.CharField(default='missing', max_length=200),
        ),
    ]
