# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_app', '0008_uploadfailure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='citation',
            name='journal',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='citation',
            name='keywords',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='citation',
            name='volume',
            field=models.CharField(max_length=200),
        ),
    ]
